project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  site-url: https://data-table-raft.netlify.app
  description: ""
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/rdatatable-community/data-table-raft
      - icon: mastodon
        href: https://fosstodon.org/@r_data_table
      - icon: cloud
        href: https://bsky.app/profile/rdatatable.bsky.social
      - icon: twitter
        href: https://twitter.com/r_data_table
      - icon: rss
        href: index.xml
      - icon: envelope
        href: "mailto:r.data.table@gmail.com"

format:
  html:
    theme: [solar, custom.scss]
    css: styles.css

editor: visual

execute: 
  freeze: auto

resources:
  - "images/*"
